### ISSUE TITLE
Missing asset/img/loading.gif

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka-s-themes/thedaily#23]
Hello,

The image `asset/img/loading.gif` used in `asset/css/lightgallery.css` (below) seems to be missing.
There is another `loader.gif`. Maybe it was intended to be used in place of the original image from https://github.com/sachinchoolur/lightGallery/tree/master/src/img ?

Either way this throws an error in the browser console.

```css
.lg-outer .lg-item {
    background:url(../img/loading.gif) center center no-repeat;
    display:none!important
}
```

Thanks and have a nice day.

Laurent Thomas
